"""
Phase 5A: Staff Management Backend API Tests
Tests CRUD operations for employees including create, update, reset PIN, reset TOTP, deactivate, and activate.
"""
import pytest
import requests
import os

BASE_URL = os.environ.get('REACT_APP_BACKEND_URL')
if BASE_URL:
    BASE_URL = BASE_URL.rstrip('/')

# Test data
TEST_EMPLOYEE_PREFIX = "TEST_"

class TestStaffManagementAPIs:
    """Staff Management Phase 5A API Tests"""
    
    @pytest.fixture(scope="class")
    def manager_token(self):
        """Get manager authentication token via PIN"""
        # First, lookup manager employee
        lookup_resp = requests.get(f"{BASE_URL}/api/employees/lookup/MGR001")
        assert lookup_resp.status_code == 200, f"Manager lookup failed: {lookup_resp.text}"
        manager = lookup_resp.json()
        
        # Authenticate with PIN
        auth_resp = requests.post(f"{BASE_URL}/api/auth/validate-pin", json={
            "employee_id": manager["id"],
            "pin": "1234"
        })
        assert auth_resp.status_code == 200, f"Manager auth failed: {auth_resp.text}"
        return auth_resp.json()["token"]
    
    @pytest.fixture(scope="class")
    def headers(self, manager_token):
        """Authorization headers"""
        return {"Authorization": f"Bearer {manager_token}"}
    
    # ========== LIST EMPLOYEES ==========
    
    def test_list_employees_endpoint(self, headers):
        """Test GET /api/employees/list returns employees list"""
        response = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        assert response.status_code == 200, f"List employees failed: {response.text}"
        
        data = response.json()
        assert "employees" in data, "Response should contain 'employees' key"
        assert isinstance(data["employees"], list), "employees should be a list"
        assert len(data["employees"]) > 0, "Should have at least one employee"
        
        # Verify employee structure
        emp = data["employees"][0]
        required_fields = ["id", "employee_id", "first_name", "last_name", "job_title", "status"]
        for field in required_fields:
            assert field in emp, f"Employee should have '{field}' field"
        
        print(f"SUCCESS: Listed {len(data['employees'])} employees")
    
    def test_list_employees_excludes_sensitive_data(self, headers):
        """Verify sensitive data is excluded from employee list"""
        response = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        assert response.status_code == 200
        
        data = response.json()
        for emp in data["employees"]:
            assert "pin_hash" not in emp, "pin_hash should be excluded"
            assert "totp_secret" not in emp, "totp_secret should be excluded"
        
        print("SUCCESS: Sensitive data excluded from employee list")
    
    # ========== CREATE EMPLOYEE ==========
    
    def test_create_employee_success(self, headers):
        """Test POST /api/employees/create creates new employee with generated PIN"""
        create_payload = {
            "first_name": "TestUser",
            "last_name": "AutoGenerated",
            "email": "test_auto@example.com",
            "phone": "07123456789",
            "job_title": "carer",
            "employment_type": "permanent",
            "contract_hours": 36
        }
        
        response = requests.post(f"{BASE_URL}/api/employees/create", json=create_payload, headers=headers)
        assert response.status_code == 200, f"Create employee failed: {response.text}"
        
        data = response.json()
        assert data["success"] is True, "Response should indicate success"
        assert "employee_id" in data, "Response should contain generated employee_id"
        assert "pin" in data, "Response should contain generated PIN"
        assert "name" in data, "Response should contain employee name"
        
        # Verify PIN format (4 digits)
        pin = data["pin"]
        assert len(pin) == 4, f"PIN should be 4 digits, got {len(pin)}"
        assert pin.isdigit(), "PIN should only contain digits"
        
        # Store for cleanup
        self.__class__.created_employee_id = data["employee_id"]
        
        print(f"SUCCESS: Created employee {data['employee_id']} with PIN {data['pin']}")
        return data
    
    def test_create_employee_required_fields(self, headers):
        """Test that first_name and last_name are required"""
        # Missing first_name
        response = requests.post(f"{BASE_URL}/api/employees/create", json={
            "last_name": "Test",
            "job_title": "carer"
        }, headers=headers)
        assert response.status_code == 422, "Should fail with missing first_name"
        
        # Missing last_name  
        response = requests.post(f"{BASE_URL}/api/employees/create", json={
            "first_name": "Test",
            "job_title": "carer"
        }, headers=headers)
        assert response.status_code == 422, "Should fail with missing last_name"
        
        print("SUCCESS: Required fields validation working")
    
    def test_create_employee_auto_generates_id(self, headers):
        """Test that employee_id is auto-generated based on job_title"""
        # Create a nurse - should get NRS prefix
        response = requests.post(f"{BASE_URL}/api/employees/create", json={
            "first_name": "TestNurse",
            "last_name": "AutoID",
            "job_title": "nurse",
            "employment_type": "permanent",
            "contract_hours": 36
        }, headers=headers)
        
        if response.status_code == 200:
            data = response.json()
            assert data["employee_id"].startswith("NRS"), f"Nurse should have NRS prefix, got {data['employee_id']}"
            self.__class__.created_nurse_id = data["employee_id"]
            print(f"SUCCESS: Nurse got ID {data['employee_id']}")
    
    # ========== UPDATE EMPLOYEE ==========
    
    def test_update_employee_success(self, headers):
        """Test PUT /api/employees/{emp_id}/update updates employee details"""
        # First, get an employee to update
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        employees = list_resp.json()["employees"]
        
        # Find a staff member (not admin/manager) to update
        test_emp = None
        for emp in employees:
            if emp["role"] == "staff" and emp.get("employment_type") != "agency":
                test_emp = emp
                break
        
        if not test_emp:
            pytest.skip("No suitable employee found for update test")
        
        # Update contract hours
        update_payload = {
            "contract_hours": 40
        }
        
        response = requests.put(
            f"{BASE_URL}/api/employees/{test_emp['id']}/update",
            json=update_payload,
            headers=headers
        )
        assert response.status_code == 200, f"Update failed: {response.text}"
        
        data = response.json()
        assert data["success"] is True
        
        # Verify the update persisted
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        updated_emp = next((e for e in list_resp.json()["employees"] if e["id"] == test_emp["id"]), None)
        assert updated_emp is not None
        assert updated_emp["contract_hours"] == 40, "Contract hours should be updated"
        
        # Restore original value
        requests.put(
            f"{BASE_URL}/api/employees/{test_emp['id']}/update",
            json={"contract_hours": test_emp.get("contract_hours", 36)},
            headers=headers
        )
        
        print(f"SUCCESS: Updated employee {test_emp['employee_id']} contract hours")
    
    def test_update_employee_not_found(self, headers):
        """Test update returns 404 for non-existent employee"""
        response = requests.put(
            f"{BASE_URL}/api/employees/non-existent-id/update",
            json={"contract_hours": 40},
            headers=headers
        )
        assert response.status_code == 404, "Should return 404 for non-existent employee"
        print("SUCCESS: Update returns 404 for non-existent employee")
    
    # ========== RESET PIN ==========
    
    def test_reset_pin_success(self, headers):
        """Test PUT /api/employees/{emp_id}/reset-pin returns new PIN"""
        # Get an employee to reset PIN
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        employees = list_resp.json()["employees"]
        
        # Find a staff member
        test_emp = next((e for e in employees if e["role"] == "staff"), None)
        if not test_emp:
            pytest.skip("No staff employee found for PIN reset test")
        
        response = requests.put(
            f"{BASE_URL}/api/employees/{test_emp['id']}/reset-pin",
            headers=headers
        )
        assert response.status_code == 200, f"Reset PIN failed: {response.text}"
        
        data = response.json()
        assert data["success"] is True
        assert "new_pin" in data, "Response should contain new_pin"
        assert "employee_id" in data, "Response should contain employee_id"
        assert "name" in data, "Response should contain employee name"
        
        # Verify PIN format
        pin = data["new_pin"]
        assert len(pin) == 4, f"PIN should be 4 digits, got {len(pin)}"
        assert pin.isdigit(), "PIN should only contain digits"
        
        print(f"SUCCESS: Reset PIN for {data['employee_id']}, new PIN: {data['new_pin']}")
    
    def test_reset_pin_not_found(self, headers):
        """Test reset PIN returns 404 for non-existent employee"""
        response = requests.put(
            f"{BASE_URL}/api/employees/non-existent-id/reset-pin",
            headers=headers
        )
        assert response.status_code == 404
        print("SUCCESS: Reset PIN returns 404 for non-existent employee")
    
    # ========== RESET TOTP ==========
    
    def test_reset_totp_success(self, headers):
        """Test PUT /api/employees/{emp_id}/reset-totp resets TOTP secret"""
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        employees = list_resp.json()["employees"]
        
        test_emp = next((e for e in employees if e["role"] == "staff"), None)
        if not test_emp:
            pytest.skip("No staff employee found for TOTP reset test")
        
        response = requests.put(
            f"{BASE_URL}/api/employees/{test_emp['id']}/reset-totp",
            headers=headers
        )
        assert response.status_code == 200, f"Reset TOTP failed: {response.text}"
        
        data = response.json()
        assert data["success"] is True
        assert "message" in data, "Response should contain message"
        
        print(f"SUCCESS: Reset TOTP for employee, message: {data['message']}")
    
    def test_reset_totp_not_found(self, headers):
        """Test reset TOTP returns 404 for non-existent employee"""
        response = requests.put(
            f"{BASE_URL}/api/employees/non-existent-id/reset-totp",
            headers=headers
        )
        assert response.status_code == 404
        print("SUCCESS: Reset TOTP returns 404 for non-existent employee")
    
    # ========== DEACTIVATE EMPLOYEE ==========
    
    def test_deactivate_employee_success(self, headers):
        """Test PUT /api/employees/{emp_id}/deactivate changes status to inactive"""
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        employees = list_resp.json()["employees"]
        
        # Find an active staff member to deactivate
        test_emp = next((e for e in employees if e["role"] == "staff" and e["status"] == "active"), None)
        if not test_emp:
            pytest.skip("No active staff employee found for deactivate test")
        
        response = requests.put(
            f"{BASE_URL}/api/employees/{test_emp['id']}/deactivate",
            headers=headers
        )
        assert response.status_code == 200, f"Deactivate failed: {response.text}"
        
        data = response.json()
        assert data["success"] is True
        
        # Verify status changed
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        updated_emp = next((e for e in list_resp.json()["employees"] if e["id"] == test_emp["id"]), None)
        assert updated_emp is not None
        assert updated_emp["status"] == "inactive", "Status should be inactive"
        
        # Store for activate test
        self.__class__.deactivated_emp_id = test_emp["id"]
        
        print(f"SUCCESS: Deactivated employee {test_emp['employee_id']}")
    
    def test_deactivate_not_found(self, headers):
        """Test deactivate returns 404 for non-existent employee"""
        response = requests.put(
            f"{BASE_URL}/api/employees/non-existent-id/deactivate",
            headers=headers
        )
        assert response.status_code == 404
        print("SUCCESS: Deactivate returns 404 for non-existent employee")
    
    # ========== ACTIVATE EMPLOYEE ==========
    
    def test_activate_employee_success(self, headers):
        """Test PUT /api/employees/{emp_id}/activate changes status to active"""
        # Use the employee we deactivated in the previous test
        emp_id = getattr(self.__class__, 'deactivated_emp_id', None)
        if not emp_id:
            pytest.skip("No deactivated employee to activate")
        
        response = requests.put(
            f"{BASE_URL}/api/employees/{emp_id}/activate",
            headers=headers
        )
        assert response.status_code == 200, f"Activate failed: {response.text}"
        
        data = response.json()
        assert data["success"] is True
        
        # Verify status changed back to active
        list_resp = requests.get(f"{BASE_URL}/api/employees/list", headers=headers)
        updated_emp = next((e for e in list_resp.json()["employees"] if e["id"] == emp_id), None)
        assert updated_emp is not None
        assert updated_emp["status"] == "active", "Status should be active"
        
        print(f"SUCCESS: Activated employee")
    
    def test_activate_not_found(self, headers):
        """Test activate returns 404 for non-existent employee"""
        response = requests.put(
            f"{BASE_URL}/api/employees/non-existent-id/activate",
            headers=headers
        )
        assert response.status_code == 404
        print("SUCCESS: Activate returns 404 for non-existent employee")
    
    # ========== AUTHORIZATION TESTS ==========
    
    def test_endpoints_require_auth(self):
        """Test that all employee management endpoints require authentication"""
        endpoints = [
            ("GET", "/api/employees/list"),
            ("POST", "/api/employees/create"),
            ("PUT", "/api/employees/test-id/update"),
            ("PUT", "/api/employees/test-id/reset-pin"),
            ("PUT", "/api/employees/test-id/reset-totp"),
            ("PUT", "/api/employees/test-id/deactivate"),
            ("PUT", "/api/employees/test-id/activate"),
        ]
        
        for method, endpoint in endpoints:
            if method == "GET":
                response = requests.get(f"{BASE_URL}{endpoint}")
            elif method == "POST":
                response = requests.post(f"{BASE_URL}{endpoint}", json={})
            else:
                response = requests.put(f"{BASE_URL}{endpoint}", json={})
            
            assert response.status_code == 401, f"{method} {endpoint} should require auth, got {response.status_code}"
        
        print("SUCCESS: All endpoints require authentication")


# Run tests
if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])
